<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Procurement;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Log;
use App\Mail\ProcurementCreatedMail;
use App\Mail\ProcurementStatusUpdatedMail;

class ProcurementController extends Controller
{
    // Create new procurement (Requires Auth)
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|email',
            'phone' => 'required|string',
            'details' => 'required|string',
        ]);

        $procurementId = 'PR' . mt_rand(10000000, 99999999);

        $procurement = Procurement::create([
            'procurement_id' => $procurementId,
            'user_id' => $request->user()->id,
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'details' => $request->details,
            'status' => 'pending',
        ]);

        try {
            Mail::to($procurement->email)->send(new ProcurementCreatedMail($procurement));
        } catch (\Throwable $e) {
            Log::error("Failed to send ProcurementCreatedMail to {$procurement->email}: " . $e->getMessage());
        }

        return response()->json([
            'message' => 'Procurement created successfully',
            'procurement' => $procurement
        ], 201);
    }

    // Get user's procurements (Requires Auth)
    public function index(Request $request)
    {
        $user = $request->user();

        // Auto-link any unlinked procurements that match this user's email
        Procurement::whereNull('user_id')
            ->where('email', $user->email)
            ->update(['user_id' => $user->id]);

        $procurements = Procurement::where(function ($q) use ($user) {
            $q->where('user_id', $user->id)
              ->orWhere('email', $user->email);
        })->latest()->get();

        return response()->json($procurements);
    }

    // Get single procurement details (Requires Auth)
    public function show(Request $request, $id)
    {
        $user = $request->user();
        if ($user->role === 'admin') {
            $procurement = $this->findProcurement($id);
        } else {
            $query = Procurement::where(function ($q) use ($user) {
                $q->where('user_id', $user->id)
                  ->orWhere('email', $user->email);
            });
            if (is_numeric($id)) {
                $procurement = $query->where(function ($q) use ($id) {
                    $q->where('id', $id)->orWhere('procurement_id', (string) $id);
                })->firstOrFail();
            } else {
                $procurement = $query->where('procurement_id', $id)->firstOrFail();
            }
        }
        return response()->json($procurement);
    }

    // Download Procurement Receipt
    public function downloadReceipt(Request $request, $id)
    {
        $user = $request->user();

        if ($user->role === 'admin') {
            $procurement = $this->findProcurement($id);
        } else {
            $query = Procurement::with('user')->where(function ($q) use ($user) {
                $q->where('user_id', $user->id)
                  ->orWhere('email', $user->email);
            });
            if (is_numeric($id)) {
                $procurement = $query->where(function ($q) use ($id) {
                    $q->where('id', $id)->orWhere('procurement_id', (string) $id);
                })->firstOrFail();
            } else {
                $procurement = $query->where('procurement_id', $id)->firstOrFail();
            }
        }

        return response()->view('receipts.procurement-receipt', [
            'procurement' => $procurement
        ], 200, [
            'Content-Type' => 'text/html; charset=UTF-8'
        ]);
    }

    // Download Procurement Invoice
    public function downloadInvoice(Request $request, $id)
    {
        $user = $request->user();

        if ($user->role === 'admin') {
            $procurement = $this->findProcurement($id);
        } else {
            $query = Procurement::with('user')->where(function ($q) use ($user) {
                $q->where('user_id', $user->id)
                  ->orWhere('email', $user->email);
            });
            if (is_numeric($id)) {
                $procurement = $query->where(function ($q) use ($id) {
                    $q->where('id', $id)->orWhere('procurement_id', (string) $id);
                })->firstOrFail();
            } else {
                $procurement = $query->where('procurement_id', $id)->firstOrFail();
            }
        }

        if (!$procurement->invoice_generated && (!$user || $user->role !== 'admin')) {
            return response()->json(['message' => 'Invoice has not been generated by admin yet.'], 403);
        }

        $cost = is_numeric($procurement->cost) ? (float)$procurement->cost : 150000;

        $items = [
            [
                'name' => $procurement->details ?? 'Procurement Item',
                'amount' => $cost
            ]
        ];

        return response()->view('invoices.invoice', [
            'invoice_number' => 'INV-' . strtoupper(substr(md5($procurement->procurement_id ?? $id), 0, 6)),
            'customer_name' => $procurement->name ?? ($procurement->user->name ?? 'Customer'),
            'invoice_date' => $procurement->created_at ? $procurement->created_at->format('d M Y') : date('d M Y'),
            'due_date' => $procurement->expected_date ? \Carbon\Carbon::parse($procurement->expected_date)->format('d M Y') : date('d M Y'),
            'items' => $items,
            'total_amount' => $cost,
            'bank_account_number' => \App\Models\Setting::get('bank_account_number', '0900779403'),
            'bank_account_name' => \App\Models\Setting::get('bank_account_name', 'Leezoe integrated'),
            'bank_name' => \App\Models\Setting::get('bank_name', 'Guaranty Trust Bank.'),
        ], 200, [
            'Content-Type' => 'text/html; charset=UTF-8'
        ]);
    }

    // Admin: Generate Invoice
    public function generateInvoice(Request $request, $id)
    {
        $procurement = $this->findProcurement($id);

        if (empty($procurement->cost) || !is_numeric($procurement->cost) || (float)$procurement->cost <= 0) {
            return response()->json([
                'message' => 'Cannot generate invoice: Procurement cost (price) has not been updated yet. Please edit the procurement details and set a cost first.'
            ], 422);
        }

        $procurement->invoice_generated = true;
        $procurement->save();

        $recipientEmail = $procurement->email ?? ($procurement->user->email ?? null);
        if ($recipientEmail) {
            try {
                Mail::to($recipientEmail)->send(new \App\Mail\InvoiceGeneratedMail($procurement, 'Procurement'));
            } catch (\Throwable $e) {
                Log::error("Failed to send InvoiceGeneratedMail to {$recipientEmail}: " . $e->getMessage());
            }
        }

        return response()->json([
            'message' => 'Procurement invoice generated successfully and notification email sent to customer.',
            'procurement' => $procurement
        ]);
    }

    private function findProcurement($id)
    {
        $query = Procurement::with('user');
        if (is_numeric($id)) {
            return $query->where(function ($q) use ($id) {
                $q->where('id', $id)->orWhere('procurement_id', (string) $id);
            })->firstOrFail();
        }
        return $query->where('procurement_id', $id)->firstOrFail();
    }

    // Admin: List all procurements
    public function adminIndex()
    {
        $procurements = Procurement::with('user')->get();
        return response()->json($procurements);
    }

    // Admin: Get single procurement
    public function adminShow($id)
    {
        $procurement = $this->findProcurement($id);
        return response()->json($procurement);
    }

    // Admin: Update procurement details & status
    public function adminUpdate(Request $request, $id)
    {
        $request->validate([
            'status' => 'nullable|string',
            'category' => 'nullable|string',
            'quantity' => 'nullable|string',
            'supplier' => 'nullable|string',
            'location' => 'nullable|string',
            'expected_date' => 'nullable|date',
            'delivered_date' => 'nullable|date',
            'recipient_location' => 'nullable|string',
            'cost' => 'nullable|numeric',
        ]);

        $procurement = $this->findProcurement($id);

        $procurement->update($request->only([
            'status',
            'category',
            'quantity',
            'supplier',
            'location',
            'expected_date',
            'delivered_date',
            'recipient_location',
            'cost',
        ]));

        $recipientEmail = $procurement->email ?? ($procurement->user->email ?? null);
        if ($recipientEmail) {
            try {
                Mail::to($recipientEmail)->send(new ProcurementStatusUpdatedMail($procurement));
            } catch (\Throwable $e) {
                Log::error("Failed to send ProcurementStatusUpdatedMail to {$recipientEmail}: " . $e->getMessage());
            }
        }

        return response()->json([
            'message' => 'Procurement updated successfully',
            'procurement' => $procurement
        ]);
    }

    // Admin: Update status
    public function updateStatus(Request $request, $id)
    {
        $request->validate([
            'status' => 'required|string'
        ]);

        $procurement = $this->findProcurement($id);
        $procurement->status = $request->status;
        $procurement->save();

        $recipientEmail = $procurement->email ?? ($procurement->user->email ?? null);
        if ($recipientEmail) {
            try {
                Mail::to($recipientEmail)->send(new ProcurementStatusUpdatedMail($procurement));
            } catch (\Throwable $e) {
                Log::error("Failed to send ProcurementStatusUpdatedMail to {$recipientEmail}: " . $e->getMessage());
            }
        }

        return response()->json([
            'message' => 'Procurement status updated',
            'procurement' => $procurement
        ]);
    }
}


